import { CalendarDays, Camera, Check, ChevronRight, Clock3, Heart, Mic, Plus, ShieldCheck, Sparkles, Sun, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SAFETY_NOTICE } from '@careloop/shared';

const Screen = ({ eyebrow, title, copy, children }: React.PropsWithChildren<{ eyebrow: string; title: string; copy: string }>) => <div className="screen">
  <p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p>{children}
</div>;
const Tile = ({ icon, title, copy, to = '#' }: { icon: React.ReactNode; title: string; copy: string; to?: string }) => <Link className="tile" to={to}>{icon}<span><strong>{title}</strong><small>{copy}</small></span><ChevronRight /></Link>;

export function WelcomePage() { return <main className="welcome"><div className="sun-orbit"><Heart /></div><p className="eyebrow">Care, connected</p><h1>Family care feels lighter when everyone is in the loop.</h1><p>One warm place for check-ins, tasks, memories and everyday support.</p><div className="button-row"><Link className="primary-button" to="/create-circle">Create a family group</Link><Link className="secondary-button" to="/join-circle">Join with a code</Link></div><small className="safety"><ShieldCheck size={16} /> {SAFETY_NOTICE}</small></main>; }
export function CreateCirclePage() { return <Screen eyebrow="Start together" title="Create your Care Circle" copy="Give your family group a familiar name."><form className="form-card"><label>Circle name<input placeholder="e.g. Amma's care circle" /></label><label>Your role<select><option>Family member</option><option>Care recipient</option><option>Coordinator</option></select></label><Link className="primary-button" to="/profile">Continue</Link></form></Screen>; }
export function JoinCirclePage() { return <Screen eyebrow="You’re invited" title="Join your family group" copy="Enter the six-character code shared by your family."><form className="form-card"><label>Invite code<input className="code-input" placeholder="CARE42" maxLength={6} /></label><Link className="primary-button" to="/profile">Join circle</Link></form></Screen>; }
export function ProfileSetupPage() { return <Screen eyebrow="A little about you" title="Make this space yours" copy="Your family will see this name and photo."><form className="form-card"><button className="avatar-picker" type="button"><Camera /> Add photo</button><label>Preferred name<input placeholder="How should we greet you?" /></label><Link className="primary-button" to="/preferences">Next</Link></form></Screen>; }
export function AgePreferencesPage() { return <Screen eyebrow="Comfort first" title="Set your preferences" copy="Choose the experience that feels easiest to use."><div className="form-card"><label>Age range<select><option>Under 18</option><option>18–64</option><option>65+</option></select></label><label className="check-row"><input type="checkbox" defaultChecked /> Larger text and controls</label><label className="check-row"><input type="checkbox" defaultChecked /> Voice-first shortcuts</label><Link className="primary-button" to="/home">Finish setup</Link></div></Screen>; }

export function PatientHomePage() { return <Screen eyebrow="Good morning, Meera" title="You’re cared for today." copy="Here’s what your family has lined up."><div className="hero-card"><Sun /><div><strong>All settled for this morning</strong><p>Priya is checking in at 10:30 AM.</p></div></div><div className="quick-grid"><Tile icon={<Mic />} title="Talk to CareLoop" copy="Share an update" to="/voice" /><Tile icon={<CalendarDays />} title="Today" copy="2 gentle reminders" to="/timeline" /><Tile icon={<Heart />} title="Wellbeing" copy="How are you feeling?" to="/wellbeing" /><Tile icon={<Camera />} title="MemoryBox" copy="See family moments" to="/memories" /></div></Screen>; }
export function FamilyHomePage() { return <Screen eyebrow="The Sharma family" title="Everyone has the same picture." copy="A calm overview of today’s care."><div className="stats"><article><strong>3</strong><span>open tasks</span></article><article><strong>2</strong><span>check-ins today</span></article><article><strong>5</strong><span>family members</span></article></div><h2>Needs attention</h2><Tile icon={<Clock3 />} title="Confirm evening visit" copy="Unassigned · Today, 6 PM" to="/tasks" /><Tile icon={<Sparkles />} title="Care handoff ready" copy="Review the latest summary" to="/timeline" /></Screen>; }
export function VoicePage() { return <Screen eyebrow="Voice companion" title="What would you like the family to know?" copy="Speak naturally. You can review everything before it is shared."><div className="voice-orb"><button aria-label="Start recording"><Mic /></button><span>Tap to talk</span></div><div className="notice"><ShieldCheck /> CareLoop can capture updates and create tasks, but cannot give medical advice or change medication.</div></Screen>; }
export function TasksPage() { return <Screen eyebrow="Shared care" title="Care tasks" copy="Clear ownership, without the family group-chat scramble."><button className="primary-button compact"><Plus /> Add a task</button><div className="list"><label className="task"><input type="checkbox" /><span><strong>Pick up prescription</strong><small>Arjun · Today, 4 PM</small></span></label><label className="task"><input type="checkbox" defaultChecked /><span><strong>Morning check-in</strong><small>Priya · Completed</small></span></label><label className="task"><input type="checkbox" /><span><strong>Book transport</strong><small>Unassigned · Tomorrow</small></span></label></div></Screen>; }
export function TimelinePage() { return <Screen eyebrow="One shared story" title="Care timeline" copy="Updates, handoffs and moments in a calm chronological view."><div className="timeline"><article><i></i><time>9:15 AM</time><strong>Morning check-in completed</strong><p>Meera is feeling cheerful and had breakfast.</p></article><article><i></i><time>Yesterday</time><strong>Handoff from Priya to Arjun</strong><p>Evening visit and pharmacy pickup confirmed.</p></article></div></Screen>; }
export function MemoryBoxPage() { return <Screen eyebrow="MemoryBox" title="Small moments, kept close." copy="Photos, voice notes and stories shared by your circle."><div className="memory-grid"><article className="memory peach"><Camera /><strong>Sunday lunch</strong><span>From Priya</span></article><article className="memory yellow"><Heart /><strong>Your favourite song</strong><span>Voice note · 0:42</span></article><button className="memory add"><Plus /> Add a memory</button></div></Screen>; }
export function CareCirclePage() { return <Screen eyebrow="Your people" title="Family circle" copy="See who’s here and when they’re available."><div className="people"><article><b>PS</b><span><strong>Priya</strong><small>Available this morning</small></span></article><article><b>AS</b><span><strong>Arjun</strong><small>Available after 5 PM</small></span></article><article><b>NK</b><span><strong>Nina</strong><small>Coordinator</small></span></article></div><button className="secondary-button"><Users /> Invite someone</button></Screen>; }
export function HealthWellbeingPage() { return <Screen eyebrow="Gentle check-in" title="How are you feeling today?" copy="This helps your family notice patterns. It is not a medical assessment."><div className="moods"><button>😊<span>Good</span></button><button>🙂<span>Okay</span></button><button>😕<span>Low</span></button><button>😣<span>Unwell</span></button></div><textarea rows={4} placeholder="Anything you want to add?" /><button className="primary-button">Share check-in</button></Screen>; }
export function SettingsPage() { return <Screen eyebrow="Your space" title="Settings" copy="Control notifications, accessibility and privacy."><div className="list"><Tile icon={<Users />} title="Circle permissions" copy="Choose who can see what" /><Tile icon={<Check />} title="Notifications" copy="Daily digest and urgent updates" /><Tile icon={<ShieldCheck />} title="Privacy & safety" copy="Data controls and boundaries" /></div></Screen>; }
